version: '3.1'

services:

  pv321.mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  pv321.mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@pv321.mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - "8089:8081"

  vp321.redis:
    image: redis
    ports:
      - "6379:6379"

  vp321.nginx:
    build:
      context: ./services/nginx
      dockerfile: ./Dockerfile
      #что бы внутри можно было читать , вставляем его как "флешку" volumes
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      #информация для docker , какие микросервисы должны быть заупещены, что бы контейнер мог работать "depends_on"
      #этот контейнер будет работаь в том случ , если остальные контейнеры будут работать
    depends_on:
      - vp321.api.csharp
      - vp321.api.express
      - vp321.api.http


  vp321.api.csharp:
    build:
      context: ./back/csharp-api
    env_file:
      - ./jwt.env


  vp321.api.express:
    build:
      context: ./back/express-api
    env_file:
      - ./jwt.env
    environment:
        - SERVER_NAME=ExpressServer
        - SERVER_PORT=4000


  vp321.api.http:
    build:
      context: ./back/http-api
    env_file:
        - ./jwt.env
    environment:
      - SERVER_NAME=HttpServer

  vp321.api.hiload1:
    build:
      context: ./back/http-api
    env_file:
        - ./jwt.env
    environment:
        - SERVER_NAME=Hiload First

  vp321.api.hiload2:
    build:
      context: ./back/http-api
    env_file:
      - ./jwt.env
    environment:
      - SERVER_NAME=Hiload Second

